### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ghost** [jonahseguin/drink#5]
I want to use your library in a project of mine but I want to make sure what I'm allowed and not allowed to do with your code

**Comment by jonahseguin** [comment]
Hi there.  Sorry there is no LICENSE currently in the repo!  Feel free to do whatever you like with the code, and I'm always open to contributions to improve the codebase.  Please provide credit when possible, and obviously don't claim the code as your own.
The goal of this project is to improve the task of writing commands for everyone within the community.

If you need any help don't hesitate to reach out.

**Comment by ghost** [comment]
Alright, Was just making sure I could make a more personalized fork to better suit my current needs. I'll make sure to provide proper credit, Thanks for clearing that up!
