### ISSUE TITLE
Doesn't let me clone the repo

### ISSUE THREAD

**Issue by Maploop** [jonahseguin/drink#9]
Bascially when I type the command to clone the repository,
I get an error saying that I don't have access to the repository.
![image](https://user-images.githubusercontent.com/76199586/108719000-461d3300-7534-11eb-999b-dddec07d9e2f.png)

**Comment by jonahseguin** [comment]
Hi, sorry for the late reply.  I'm not sure what would cause this.  The repository is public.
Try cloning with the HTTP url instead maybe?

**Comment by Maploop** [comment]
Hey

Thanks for the reply, I stopped trying after I made this issue, it was fixed using the HTTP url.
![image](https://user-images.githubusercontent.com/76199586/118352078-b60bea00-b574-11eb-937d-e30f8aa5b5c8.png)
